### ISSUE TITLE
Allow user to specify an output directory.

### ISSUE THREAD

**Issue by IcySon55** [mmozeiko/pkg2zip#10]
Previously I was using pkg_dec with NPS Browser (I also contributed to NPSB) and it had the option to provide an output directroy for extracted files.

I'd like to be able to do the same thing with pkg2zip since it organizes the files in a much cleaner way.

Right now we get a single ``app`` and ``addcont`` directory where all the games end up. I'd much rather extract games into their own directories like this:

```
{gameTitle} ({region}) [{titleID}]
 |-addcont
 |-app
 \-license
```

i.e. pkg2zip -x {pkgFile} {zRifKey} -o ".\\{gameTitle} ({region}) [{titleID}]"

Thanks!

**Comment by tomazzz369** [comment]
remove -x. because that is the best way for extraction. i can extract for example 20-30 dlcs to proper directory structure instead of 20-30 separated directories

**Comment by mmozeiko** [comment]
Imho this should be changed in NPS browser, not in pkg2zip. NPS browser can itself create whatever folder it wants and run pkg2zip in this folder.
