### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by usernatilds** [mmozeiko/pkg2zip#15]
I try run make when compile, but make install not work here, i now know how to install this package.

**Comment by mmozeiko** [comment]
I do not have `install` step in makefile. You'll need to either add it to makefile, or write custom install step in debian package build decription file (not sure how it is called). For example, see what I did in ArchLinux build file: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pkg2zip#n19 (line 19).

**Comment by usernatilds** [comment]
Already running ./pkg2zip in same folder, but ok.

A package in Debian distros based is a suggestion.

Thanks.
