### ISSUE TITLE
Issue when retrieving name of PKG using -l command

### ISSUE THREAD

**Issue by tegaidogun** [mmozeiko/pkg2zip#35]
Whenever I used the -l command to run the program, it always returned this error in the console on Windows :

```
This version of C:\Users\otega\Downloads\pkg2zip.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

**Comment by mmozeiko** [comment]
That probably means you're trying to 64-bit binary on 32-bit Windows (or on ARM Windows).

**Comment by tegaidogun** [comment]
Yeah, sorry. I didn't bother to read the error message at the time when I was checking something. Thanks for replying.
