### ISSUE TITLE
issues on extraction patch

### ISSUE THREAD

**Issue by tomazzz369** [mmozeiko/pkg2zip#4]
pkg2zip v1.6 error seems to only on patch extraction (no zip file). without -x arg extraction working fine

pkg2zip.exe -x mypkgfile.pkg (same with added zrif)

...
[23/24] sce_pfs/pflist
[24/24] sce_sys/package/digs.bin
ERROR: cannot create 'patch/PCSE00680/sce_sys/package/digs.bin' file

http://gs.ww.np.dl.playstation.net/ppkg/np/PCSE00680/PCSE00680_T0/ee26b55db65c4b41/UP4403-PCSE00680_00-SPARKLEUNLEASHED-A0101-V0101-1274bf4b92dce125081c8ee295d999fe51a96887-PE.pkg
or
http://gs.ww.np.dl.playstation.net/ppkg/np/PCSE00339/PCSE00339_T2/f75debdfce6af542/UP3643-PCSE00339_00-DUKE3DHDUSVITA00-A0101-V0102-8f63a6108a67372a2cf8b55eb78f55ad763c69aa-PE.pkg

**Comment by mmozeiko** [comment]
You are right. Patch unpacking with "-x" doesn't work :(

I'll fix it. For now try it without -x, it should work.

**Comment by tomazzz369** [comment]
i'm not familiar with psx stuff, but tool extracts only 2 files (DOCUMENT.DAT, EBOOT.PBP) instead 16. reast are not needed on ps vita? with and without -x

pkg2zip v1.6

[*] loading...
[*] unpacking PSX
[*] output to 'Constructor [NPEF00057] [PSX]' folder
[*] decrypting...
[1/16] PS3LOGO.DAT
[2/16] PARAM.SFO
[3/16] ICON0.PNG
[4/16] PIC0.PNG
[5/16] PIC1.PNG
[6/16] PIC2.PNG
[7/16] USRDIR
[8/16] USRDIR/CONTENT
[9/16] USRDIR/SAVEDATA
[10/16] USRDIR/CONTENT/DOCUMENT.DAT
[11/16] USRDIR/CONTENT/EBOOT.PBP
[12/16] USRDIR/ISO.BIN.EDAT
[13/16] USRDIR/SAVEDATA/ICON0.PNG
[14/16] USRDIR/SAVEDATA/PARAM.SFO
[15/16] USRDIR/SAVEDATA/SCEVMC0.VMP
[16/16] USRDIR/SAVEDATA/SCEVMC1.VMP
[*] done!

**Comment by mmozeiko** [comment]
That is normal. Rest of files are not needed.

**Comment by tomazzz369** [comment]
ok. regards

**Comment by mmozeiko** [comment]
Fixed in 072c330. Check the v1.7 release.
