### ISSUE TITLE
Error with PSX PKG

### ISSUE THREAD

**Issue by chronoss09** [mmozeiko/pkg2zip#6]
I tested the last version with one PSX PKG

<a href="https://gyazo.com/a9158c091073586b3f797101b4c94e56"><img src="https://i.gyazo.com/a9158c091073586b3f797101b4c94e56.png" alt="https://gyazo.com/a9158c091073586b3f797101b4c94e56" width="652"/></a>

It's a PS3 format not a PSP format, so, how must i installed it ?

**Comment by mmozeiko** [comment]
Why do you think this is PSX game and not PSP game?

Did you use this pkg file:  http://zeus.dl.playstation.net/cdn/EP0102/ULES00235_00/A3mRvroTbNUUWp8MPnS2WE0abKI7POcceJDBhBjgdIbLWhHHKgN1JuoI0U90tdWH9iEqICRWxM1jbYYvlW6AXsBxLrTjODPecY9YS.pkg  ?

Few other tools I tried reports to my that this is PSP game, and not PSX. And PSP is not yet fully supported by pkg2zip.

**Comment by chronoss09** [comment]
Yes, it's this link and it's a PSX game on my Vita, buy to ps store

**Comment by tomazzz369** [comment]
of course this is psp game compatible with ps vita

https://www.gamefaqs.com/psp/928337-street-fighter-alpha-3-max/data

quote from pss "Widely considered to be the best fighting game for the PSP"

**Comment by chronoss09** [comment]
Ok, i tested with a good PSX PKG and it work 👍 , thanks
