### ISSUE TITLE
Consider renaming?

### ISSUE THREAD

**Issue by JohnVeness** [mmozeiko/pkg2zip#8]
This tool now does much more than outputting to zip, including outputting to an extracted folder, or to ISO/CSO. So maybe it should be renamed pkgtool or similar? Or pspkgtool to make it clear it is PlayStation-specific, as opposed to other types of PKG files.

**Comment by mmozeiko** [comment]
That's why I didn't want (and still don't) to have non-zip mode... blame Radziu.

**Comment by tomazzz369** [comment]
Just don't use -x on extraction and you have pkg > zip, problem solved. I always use non-zip mode if game have small amount of files.

**Comment by mmozeiko** [comment]
Its not about using or not using extra argument. Its about maintaining/testing extra code (which I do not have use for).

**Comment by JohnVeness** [comment]
I didn't mean to start a debate over the functionality of the program, just its name! You're free to have it do whatever you want, but as I saw the latest update would convert PSP pkgs to ISO or CSO, and as I already knew about the -x option previously added, I thought you were expanding the program to do more and more. It was only for that reason that I suggested thinking about the name.

**Comment by tomazzz369** [comment]
ok. but i'm grateful for non-zip option. thanks for your hard work. regards
